# Generated by Django 4.1.2 on 2022-10-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_blogpost"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
